plugins { id "com.android.application" }

android {
  namespace "ai.comma.remotehud"
  compileSdk 35
  defaultConfig {
    applicationId "ai.comma.remotehud"
    minSdk 26
    targetSdk 35
    versionCode 95
    versionName "0.80-model-gl-v2"
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }
}
