plugins { id "com.android.application" }

android {
  namespace "ai.comma.remotehud"
  compileSdk 35
  defaultConfig {
    applicationId "ai.comma.remotehud"
    minSdk 26
    targetSdk 35
    versionCode 84
    versionName "0.69-top-anchor"
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }
}
