plugins { id "com.android.application" }

def hudVersionCode = (System.getenv("NAVER_HUD_VERSION_CODE") ?: "1").toInteger()
def hudVersionName = System.getenv("NAVER_HUD_VERSION_NAME") ?: "0.1-6.10.0.16"

android {
  namespace "ai.comma.naverhud"
  compileSdk 35
  buildToolsVersion "35.0.1"
  defaultConfig {
    applicationId "ai.comma.naverhud"
    minSdk 26
    targetSdk 35
    versionCode hudVersionCode
    versionName hudVersionName
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }
}

dependencies {
  compileOnly "de.robv.android.xposed:api:82"
}
